/**
 * Seed data for the product catalog (§7.4).
 *
 * Navigate Portal pricing — sourced from the Portal Pricing Calculator tool.
 * Covers the platform baseline, five core portal products (two with premium
 * feature add-ons), and 23 buy-up / integration add-ons.
 *
 * This module is loaded lazily by productService.resetCatalog() and directly
 * by the seed runner (seeds/index.js).
 *
 * NOTE: productLineId fields are resolved by name at runtime inside
 * seedProductCatalog() below, so this data is safe to export as a plain array.
 */

/**
 * Products with productLineName for seed resolution.
 * At runtime, productLineName is converted to a real productLineId.
 */
const productCatalogSeed = [
  // ── Baseline ───────────────────────────────────────────────────────────────
  {
    name: "Navigate Platform Baseline",
    sku: "NAV-BASE-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 25000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: true,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.2,
        implPrice: 40000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.13,
        implPrice: 53200,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.07,
        implPrice: 66400,
      },
    ],
    description:
      "Core PMPM pricing and one-time implementation fee that establishes access to the Navigate platform, independent of selected portal tier or buy-up. Applied once when any portal product is selected.",
  },

  // ── Core Portal Products ───────────────────────────────────────────────────
  {
    name: "Member Portal",
    sku: "NAV-MBR-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 16000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.1,
        implPrice: 22000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.07,
        implPrice: 29260,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.03,
        implPrice: 36520,
      },
    ],
    description: "Self-service portal for health plan members.",
  },
  {
    name: "Member Portal - Premium Features",
    sku: "NAV-MBR-PREM-001",
    productLineName: "Health Portals",
    compatibleCoreName: "Member Portal",
    type: "Child",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 4000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.03,
        implPrice: 3000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.02,
        implPrice: 3990,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.01,
        implPrice: 4980,
      },
    ],
    description:
      "Delta pricing above Member Portal base tier. Adds: Authorization & Referrals, Gaps in Care, Prescription History, Financial Management, and Care Plan.",
  },
  {
    name: "Member Mobile App",
    sku: "NAV-APP-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 12000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.05,
        implPrice: 13000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.03,
        implPrice: 17290,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.02,
        implPrice: 21580,
      },
    ],
    description:
      "Member Mobile App extending the Navigate platform experience to mobile devices.",
  },
  {
    name: "Provider Portal",
    sku: "NAV-PRV-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 30000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.1,
        implPrice: 22000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.07,
        implPrice: 29260,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.03,
        implPrice: 36520,
      },
    ],
    description: "Portal for healthcare providers and networks.",
  },
  {
    name: "Provider Portal - Premium Features",
    sku: "NAV-PRV-PREM-001",
    productLineName: "Health Portals",
    compatibleCoreName: "Provider Portal",
    type: "Child",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 8000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.05,
        implPrice: 9000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.03,
        implPrice: 11970,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.02,
        implPrice: 14940,
      },
    ],
    description:
      "Delta pricing above Provider Portal base tier. Adds: Claims - Submit & Status, Member Care Plan, Provider Scorecard, Authorizations & Referrals, Provider Attestation, Gaps in Care, and Prescription History.",
  },
  {
    name: "Employer Portal",
    sku: "NAV-EMP-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 25000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.04,
        implPrice: 12000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.03,
        implPrice: 15960,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.01,
        implPrice: 19920,
      },
    ],
    description:
      "Full-featured Employer Portal providing a complete experience without tiering or feature segmentation.",
  },
  {
    name: "Broker Portal",
    sku: "NAV-BRK-001",
    productLineName: "Health Portals",
    type: "Core",
    pricingModel: "PMPM",
    pricingStrategy: "Volume Bands",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 20000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [
      {
        label: "1 – 50,000 members",
        maxMembers: 50000,
        price: 0.04,
        implPrice: 12000,
      },
      {
        label: "50,001 – 250,000 members",
        maxMembers: 250000,
        price: 0.03,
        implPrice: 15960,
      },
      {
        label: "250,001+ members",
        maxMembers: null,
        price: 0.01,
        implPrice: 19920,
      },
    ],
    description:
      "Full-featured Broker Portal providing a complete experience without tiering or feature segmentation.",
  },

  // ── Buy-ups / Add-ons ──────────────────────────────────────────────────────
  {
    name: "Custom Express Request Form (ExR)",
    sku: "NAV-EXR-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "PMPM",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "Implementation Only",
    basePrice: 0.01,
    unitCost: 5000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Custom-built portal forms that streamline data collection and automate delivery of submissions to customers on a recurring basis. PMPM and implementation fee are multiplied by quantity of forms.",
  },
  {
    name: "Consumer Provider Search (Provider Directory)",
    sku: "NAV-CPS-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "PMPM",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0.03,
    unitCost: 40000,
    implementationFee: 62500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Public and authenticated provider directory enabling members to search for providers by location, age, gender, specialty, and more.",
  },
  {
    name: "mPulse Member ID Card",
    sku: "NAV-IDC-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Integrated Member ID Card solution leveraging Communicate to generate and deliver digital ID cards within the Navigate portal experience.",
  },
  {
    name: "mPulse Digital Wallet",
    sku: "NAV-DW-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      'Digital wallet solution integrated with mPulse Member ID Card for secure and convenient member transactions. Requires "mPulse Member ID Card".',
  },
  {
    name: "mPulse Explanation of Benefits (EOB)",
    sku: "NAV-EOB-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Integrated EOB solution leveraging Communicate to generate and deliver Explanation of Benefits documents within the Navigate portal experience.",
  },
  {
    name: "mPulse Explanation of Payment (EOP)",
    sku: "NAV-EOP-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Integrated EOP solution leveraging Communicate to generate and deliver Explanation of Payment documents within the Navigate portal experience.",
  },
  {
    name: "mPulse Streaming Health Content",
    sku: "NAV-SHC-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "PMPM",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0.02,
    unitCost: 30000,
    implementationFee: 2500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Integrated streaming health content solution delivering personalized, on-demand educational experiences within the Navigate portal.",
  },
  {
    name: "mPulse Chat",
    sku: "NAV-CHAT-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "PMPM",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0.02,
    unitCost: 15000,
    implementationFee: 22500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Embedded chat capability delivered as a white-label solution, supporting real-time communication between users and support teams.",
  },
  {
    name: "mPulse Engagement - Member Registration",
    sku: "NAV-ENG-REG-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Targeted engagement program designed to drive member registration and onboarding through personalized outreach and activation strategies.",
  },
  {
    name: "mPulse Engagement - Member Utilization",
    sku: "NAV-ENG-UTL-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Ongoing engagement program designed to increase portal utilization through personalized, behavior-driven outreach and reminders.",
  },
  {
    name: "Single Sign On (SSO) Inbound - SAML",
    sku: "NAV-SSO-IN-SAML-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 500,
    unitCost: 2000,
    implementationFee: 11250,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Standard SSO integration enabling seamless authentication between the Navigate portal and commonly used third-party systems (inbound SAML).",
  },
  {
    name: "Single Sign On (SSO) Inbound - OAuth 2.0",
    sku: "NAV-SSO-IN-OAUTH-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 500,
    unitCost: 2500,
    implementationFee: 16250,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Standard SSO integration enabling seamless authentication between the Navigate portal and commonly used third-party systems (inbound OAuth 2.0).",
  },
  {
    name: "Single Sign On (SSO) Outbound - SAML",
    sku: "NAV-SSO-OUT-SAML-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 500,
    unitCost: 2000,
    implementationFee: 10500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Standard SSO integration enabling seamless authentication between the Navigate portal and commonly used third-party systems (outbound SAML).",
  },
  {
    name: "Single Sign On (SSO) Outbound - OAuth 2.0",
    sku: "NAV-SSO-OUT-OAUTH-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 500,
    unitCost: 2500,
    implementationFee: 15500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Standard SSO integration enabling seamless authentication between the Navigate portal and commonly used third-party systems (outbound OAuth 2.0).",
  },
  {
    name: "Language Translation",
    sku: "NAV-LANG-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "Implementation Only",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Multilingual support enabling members to access the portal in their preferred language through third-party translation services. Pricing based on partner pricing for membership, language requirements, and integration method.",
  },
  {
    name: "Integration - Member ID Card",
    sku: "NAV-INT-IDC-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "One-Time",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 2500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Third-party Member ID Card integration enabling retrieval and display of ID cards from external vendor systems within the Navigate portal.",
  },
  {
    name: "Integration - Explanation of Benefits (EOB)",
    sku: "NAV-INT-EOB-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "One-Time",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 2500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Third-party EOB solution to deliver Explanation of Benefits documents within the Navigate portal experience.",
  },
  {
    name: "Integration - Explanation of Payment (EOP)",
    sku: "NAV-INT-EOP-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Flat Fee",
    pricingStrategy: "Standard",
    billingType: "One-Time",
    scopeBasedPricing: "None",
    basePrice: 0,
    unitCost: 0,
    implementationFee: 2500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Third-party EOP solution to deliver Explanation of Payment documents within the Navigate portal experience.",
  },
  {
    name: "Integration - Identity Provider (IDP)",
    sku: "NAV-INT-IDP-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 500,
    unitCost: 2000,
    implementationFee: 25000,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Third-party identity provider (IDP) integration enabling authentication through external member or provider identity systems within the Navigate platform.",
  },
  {
    name: "Integration - Clinical Care Criteria (MCG or InterQual)",
    sku: "NAV-INT-CCC-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "PMPM",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 0.01,
    unitCost: 8000,
    implementationFee: 12500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Third-party clinical care criteria integration enabling access to MCG or InterQual guidelines within the Navigate portal experience.",
  },
  {
    name: "Integration - APIs (mPulse Hosted)",
    sku: "NAV-INT-API-HOST-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "Implementation Only",
    basePrice: 6000,
    unitCost: 5000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Custom third-party API integration where mPulse hosts the endpoints.",
  },
  {
    name: "Integration - APIs (External Host)",
    sku: "NAV-INT-API-EXT-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "Implementation Only",
    basePrice: 6000,
    unitCost: 5000,
    implementationFee: 0,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: true,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Custom third-party API integration where the third-party hosts the endpoints.",
  },
  {
    name: "Integration - Chat",
    sku: "NAV-INT-CHAT-001",
    productLineName: "Health Portals",
    type: "Add-on",
    pricingModel: "Monthly Fee",
    pricingStrategy: "Standard",
    billingType: "Recurring (Monthly)",
    scopeBasedPricing: "None",
    basePrice: 600,
    unitCost: 2500,
    implementationFee: 2500,
    overagePrice: 0,
    isBaselineProduct: false,
    isQuantityBased: false,
    inheritTierVolumesFromCore: false,
    tiers: [],
    volumeBands: [],
    description:
      "Chat integration capability supporting connection to third-party messaging platforms for embedded real-time communication within the portal.",
  },
];

/**
 * Seed function — resolves productLine names to IDs and inserts products.
 * Skips if products already exist.
 *
 * @param {import("mongoose").Model} Product
 * @param {import("mongoose").Model} ProductLine
 */
async function seedProductCatalog(Product, ProductLine) {
  const count = await Product.countDocuments();
  if (count > 0) {
    console.log(`  Products: ${count} already exist — skipping seed.`);
    return;
  }

  // Build name → _id map
  const lines = await ProductLine.find({}, "_id name").lean();
  const lineMap = {};
  for (const line of lines) {
    lineMap[line.name] = line._id;
  }

  const docs = productCatalogSeed.map(
    ({ productLineName, compatibleCoreName, ...rest }) => ({
      ...rest,
      productLineId: productLineName
        ? (lineMap[productLineName] ?? null)
        : null,
    }),
  );

  await Product.insertMany(docs);
  console.log(`  Products: inserted ${docs.length} records.`);

  // Second pass — resolve compatibleCoreName → compatibleCoreIds
  const coreNameEntries = productCatalogSeed.filter(
    (p) => p.compatibleCoreName,
  );
  if (coreNameEntries.length > 0) {
    const coreNames = [
      ...new Set(coreNameEntries.map((p) => p.compatibleCoreName)),
    ];
    const cores = await Product.find(
      { name: { $in: coreNames } },
      "_id name",
    ).lean();
    const coreMap = {};
    for (const core of cores) {
      coreMap[core.name] = core._id;
    }
    for (const entry of coreNameEntries) {
      const coreId = coreMap[entry.compatibleCoreName];
      if (coreId) {
        await Product.updateOne(
          { sku: entry.sku },
          { $set: { compatibleCoreIds: [coreId] } },
        );
      }
    }
    console.log(
      `  Products: resolved compatibleCoreIds for ${coreNameEntries.length} child product(s).`,
    );
  }
}

/**
 * Plain array export for productService.resetCatalog().
 * productLineId fields are omitted — reset uses name resolution inside resetCatalog.
 */
module.exports = productCatalogSeed;
module.exports.seedProductCatalog = seedProductCatalog;
